src/main/java/org/folio/roles/integration/keyclock/KeycloakPolicyService.java, src/main/resources/reference-data/policies/time-policies.json, src/test/java/org/folio/roles/integration/keyclock/KeycloakPolicyServiceTest.java
Error during enabling application to the tenant if policy already exists
- Do not throw error for 409 status code in keycloak and just proceed with an assignment cause policy already exists
environment. Communication is …
=> Error during enabling application to tenant if policy already exists

descriptors/ModuleDescriptor-template.json
In application descriptor mod-roles-keycloak's MD uses 5.6 version of permissions interface.
- update 'permissions' version '5.5' -> '5.6'
environment. Communication is paramount if that is to be achieved, especially as the …
=> FIX: actualize required interfaces versions

src/main/resources/swagger.api/schemas/capability/role/roleCapabilitiesRequest.json, src/main/resources/swagger.api/schemas/capability/role/roleCapabilitySetsRequest.json, src/main/resources/swagger.api/schemas/capability/user/userCapabilitiesRequest.json, src/main/resources/swagger.api/schemas/capability/user/userCapabilitySetsRequest.json, src/test/java/org/folio/roles/it/RoleCapabilityIT.java, src/test/java/org/folio/roles/it/RoleCapabilitySetIT.java, src/test/java/org/folio/roles/it/UserCapabilityIT.java, src/test/java/org/folio/roles/it/UserCapabilitySetIT.java
Remove an upper limit for role/user capability/capability-set assigment.
US: [MODROLESKC-145](https://folio-org.atlassian.net/browse/MODROLESKC-145)
- Fix validation in the swagger schema
- Adjust integration tests error messages …
=> MODROLESKC-145 Remove upper limit for role/user capability assigment

src/main/java/org/folio/roles/integration/keyclock/KeycloakRoleService.java, src/main/java/org/folio/roles/service/reference/RolesDataLoader.java, src/main/java/org/folio/roles/service/role/RoleService.java, src/test/java/org/folio/roles/integration/keyclock/KeycloakRoleServiceTest.java, src/test/java/org/folio/roles/service/reference/RolesDataLoaderTest.java, src/test/java/org/folio/roles/service/role/RoleServiceTest.java
Fix loading reference data multiple times
Role on the Keycloak side is created with new generated ID in any case, therefore check for existence is by role name
Tested locally.
Before:
After:
environment. Communication is …
=> [MODROLESKC-150]: fix loading reference data multiple times

src/main/resources/changelog/changelog-master.xml, src/main/resources/changelog/changes/adjust-update-fields-of-auditable-info.xml, src/test/java/org/folio/roles/repository/BasePolicyEntityRepositoryIT.java, src/test/java/org/folio/roles/repository/CapabilityRepositoryIT.java, src/test/java/org/folio/roles/repository/CapabilitySetRepositoryIT.java, src/test/java/org/folio/roles/repository/LoadablePermissionRepositoryIT.java, src/test/java/org/folio/roles/repository/LoadableRoleRepositoryIT.java, src/test/java/org/folio/roles/repository/RoleCapabilityRepositoryIT.java, src/test/java/org/folio/roles/repository/RoleCapabilitySetRepositoryIT.java, src/test/java/org/folio/roles/repository/RoleEntityRepositoryIT.java, src/test/java/org/folio/roles/repository/UserCapabilityRepositoryIT.java, src/test/java/org/folio/roles/repository/UserCapabilitySetRepositoryIT.java, src/test/java/org/folio/roles/repository/UserRoleRepositoryIT.java
Set `updatedBy` to the same value as `createdBy` in migration script
[MODROLESKC-8](https://folio-org.atlassian.net/browse/MODROLESKC-8)
* add a command to migration script to set `updatedBy` to the same value as `createdBy`
* adjust repository tests accordingly
Ideally, all the PRs involved in breaking changes would be merged on the same …
=> MODROLESKC-8 Set updatedBy to the same value as createdBy in migration script

NEWS.md, src/main/resources/folio-permissions/mappings-overrides.json, src/test/java/org/folio/roles/integration/kafka/CapabilityEventProcessorTest.java
https://folio-org.atlassian.net/browse/EUREKA-96
`invoices.bypass-acquisition-units` permission cannot be resolved.
- add mapping for the permission
environment. Communication is paramount if that is to be achieved, …
=> EUREKA-96: add permission mapping

NEWS.md, README.md, src/main/java/org/folio/roles/integration/keyclock/KeycloakRoleService.java, src/main/java/org/folio/roles/repository/LoadableRoleRepository.java, src/main/java/org/folio/roles/repository/RoleEntityRepository.java, src/main/java/org/folio/roles/service/CustomTenantService.java, src/main/java/org/folio/roles/service/loadablerole/LoadableRoleService.java, src/main/resources/application.yml, src/test/java/org/folio/roles/integration/keyclock/KeycloakRoleServiceTest.java, src/test/java/org/folio/roles/service/CustomTenantServiceTest.java, src/test/java/org/folio/roles/service/loadablerole/LoadableRoleServiceTest.java, src/test/resources/application-it.yml
[MODROLESKC-196](https://folio-org.atlassian.net/browse/MODROLESKC-196)
Mod-Roles-Keycloak creates default roles during the tenant enabling with load ref enabled. Roles stored on the realm realm in Keycloak can't be automatically cleaned during the application disabled with flag purge=true. It can bring to the inconsistent state in Keycloak and a situation when roles exist in Keycloak but modules DB is purged.
- Extend tenant service and clean related roles in Keycloak during the disabling with flag purge=true
- Update tests …
=> MODROLESKC-196: Clean default roles in Keycloak during the tenant disable with purge=true

src/main/java/org/folio/roles/utils/UpdateOperationHelper.java, src/test/java/org/folio/roles/service/capability/RoleCapabilityServiceTest.java, src/test/java/org/folio/roles/service/capability/RoleCapabilitySetServiceTest.java, src/test/java/org/folio/roles/service/capability/UserCapabilityServiceTest.java, src/test/java/org/folio/roles/service/capability/UserCapabilitySetServiceTest.java, src/test/java/org/folio/roles/service/role/UserRoleServiceTest.java, src/test/java/org/folio/roles/utils/UpdateOperationHelperTest.java
Removes a BadRequest error when user provides the same data for upgrade operation in user-role, role-capability, user-capability relations.
- Remove error on update operation
environment. Communication is paramount if that …
=> MODROLESKC-206 Remove error on update operation

src/main/resources/folio-permissions/mappings-overrides.json
Extend Okapi mapping overrides with new permissions/permission sets
* add permission mapping reported by `folio-module-descriptor-validator` in `mod-okapi-facade`:
```json
[ {
"key" : "Permission name is not valid",
"value" : "okapi.proxy.modules.list"
}, {
"key" : "Permission name is not valid",
"value" : "okapi.proxy.cleanup.modules"
}, {
"key" : "Permission name is not valid",
"value" : "okapi.proxy.tenants.list"
}, {
"key" : "Permission name is not valid",
"value" : "okapi.proxy.tenants.install.list"
}, {
"key" : "Permission name is not valid",
"value" : "okapi.proxy.tenants.modules.list"
}, {
"key" : "Permission name is not valid",
"value" : "okapi.proxy.tenants.interfaces.list"
}, {
"key" : "Permission name is not valid",
"value" : "okapi.proxy.tenants.timers.list"
}, {
"key" : …
```
=> MODOKAPFAC-4 Extend Okapi mapping overrides

src/main/java/org/folio/roles/controller/RoleCapabilityController.java, src/main/java/org/folio/roles/controller/RoleCapabilitySetController.java, src/main/java/org/folio/roles/service/capability/ApiRoleCapabilityService.java, src/main/java/org/folio/roles/service/capability/ApiRoleCapabilitySetService.java, src/main/java/org/folio/roles/service/capability/RoleCapabilityService.java, src/main/java/org/folio/roles/service/capability/RoleCapabilityServiceImpl.java, src/main/java/org/folio/roles/service/capability/RoleCapabilitySetService.java, src/main/java/org/folio/roles/service/capability/RoleCapabilitySetServiceImpl.java, src/main/java/org/folio/roles/utils/CapabilityUtils.java, src/main/resources/swagger.api/schemas/capability/capabilitiesUpdateRequest.json, src/main/resources/swagger.api/schemas/capability/capabilitySetsUpdateRequest.json, src/test/java/org/folio/roles/controller/RoleCapabilityControllerTest.java, src/test/java/org/folio/roles/controller/RoleCapabilitySetControllerTest.java, src/test/java/org/folio/roles/it/RoleCapabilityIT.java, src/test/java/org/folio/roles/it/RoleCapabilitySetIT.java, src/test/java/org/folio/roles/service/capability/RoleCapabilityServiceImplTest.java, src/test/java/org/folio/roles/service/capability/RoleCapabilitySetServiceImplTest.java, src/test/java/org/folio/roles/support/CapabilitySetUtils.java, src/test/java/org/folio/roles/support/CapabilityUtils.java
[[MODROLESKC-211] Implement api to update roleCapabilities and roleCapabilitySets by name](https://folio-org.atlassian.net/browse/MODROLESKC-211)
- Refactor update endpoint payloads to accept both capability and capabilitySet ids and names
- Update unit and integraton tests
=> [MODROLESKC-211] Implement api to update roleCapabilities and roleCapabilitySets by name

src/main/java/org/folio/roles/service/CustomTenantService.java, src/test/java/org/folio/roles/it/LoadableRoleProcessingIT.java, src/test/java/org/folio/roles/it/MigrationIT.java, src/test/java/org/folio/roles/it/PolicyIT.java, src/test/java/org/folio/roles/it/ReferenceDataIT.java, src/test/java/org/folio/roles/it/ReferenceRoleLoadingIT.java, src/test/java/org/folio/roles/it/RoleCapabilityIT.java, src/test/java/org/folio/roles/it/RoleCapabilitySetIT.java, src/test/java/org/folio/roles/it/RoleCapabilitySetUpdateIT.java, src/test/java/org/folio/roles/it/RoleCapabilityUpdateIT.java, src/test/java/org/folio/roles/it/RoleKeycloakIT.java, src/test/java/org/folio/roles/it/UserCapabilityIT.java, src/test/java/org/folio/roles/it/UserCapabilitySetIT.java, src/test/java/org/folio/roles/it/UserCapabilitySetUpdateIT.java, src/test/java/org/folio/roles/it/UserCapabilityUpdateIT.java, src/test/java/org/folio/roles/it/UserRolesIT.java, src/test/java/org/folio/roles/service/CustomTenantServiceTest.java
Fix an issue when new tenant is created but `mod-roles-keycloak` uses cached Keycloak token which doesn't include information about the new tenant
US: [EUREKA-338](https://folio-org.atlassian.net/browse/EUREKA-338)
* obtain a new token during tenant enabling, just after a DB update and before any interactions with Keycloak
* in integration tests that work with test keycloak realms, refresh token before each test
- Are the …
=> EUREKA-338 (evrk2) Cannot enable app-platform-minimal with reference data on a new tenant

src/main/java/org/folio/roles/mapper/KeycloakPolicyMapper.java, src/main/resources/reference-data/policies/time-policies.json, src/main/resources/swagger.api/schemas/policy/policyLogicType.json, src/main/resources/swagger.api/schemas/policy/userPolicy.json, src/main/resources/swagger.api/schemas/role/roleType.json, src/test/resources/json/reference-data/roles/librarian-support-role.json, src/test/resources/json/reference-data/roles/user-support-role.json
[[MODROLESKC-216] Make all enum values in endpoints response with upper case as stored in DB
](https://folio-org.atlassian.net/browse/MODROLESKC-216)
Rename all enums and their usages
State before:
In DB all enum values stored in upper case
=> [MODROLESKC-216] Make all enum values in endpoints response with upper case as stored in DB

src/main/java/org/folio/roles/service/role/RoleService.java, src/test/java/org/folio/roles/it/RoleKeycloakIT.java
https://folio-org.atlassian.net/browse/MODROLESKC-226
Currently role is not taking into payload role name
- Set roleType before saving
environment. Communication is paramount if that is to be achieved, especially as the …
=> [MODROLESKC-226]- Fix setting role type from payload

src/main/java/org/folio/roles/integration/kafka/CapabilityEventProcessor.java, src/test/java/org/folio/roles/integration/kafka/CapabilityEventProcessorTest.java
Fix capability set creation for permission set with `subPermissions` containing another permission set
Get `PermissionData` from mapping overrides first during capability set creation
environment. Communication is paramount …
=> MODUSERSKC-52: get PermissionData from mapping overrides first during capability set creation

src/main/java/org/folio/roles/integration/kafka/CapabilityEventProcessor.java, src/test/java/org/folio/roles/integration/kafka/CapabilityEventProcessorTest.java, src/test/java/org/folio/roles/it/KafkaMessageListenerIT.java
Create capability set with its permission for UI modules
While it's helpful …
=> MODUSERSKC-52: Create capability set with its permission for UI modules

src/main/java/org/folio/roles/service/capability/CapabilityReplacementsService.java, src/test/java/org/folio/roles/service/capability/CapabilityReplacementsServiceTest.java
Avoid null-pointer exceptions in case permission mapping overrides don't provide new name for a permission. …
=> MODROLESKC-231: fix for null-pointer exception

src/main/java/org/folio/roles/repository/CapabilityRepository.java, src/main/java/org/folio/roles/service/capability/CapabilityService.java, src/test/java/org/folio/roles/it/PermissionsUserIT.java, src/test/java/org/folio/roles/service/capability/CapabilityServiceTest.java, src/test/resources/sql/capabilities/populate-capability-permissions.sql
FOLIO Permissions can be renamed via a new "replaces" property.  The Eureka platform should honor this property.
https://folio-org.atlassian.net/browse/MODROLESKC-221
- change SQL to request user permissions
- add SQL for querying desired permission
- adjust tests by test cases
=> MODROLESKC-221: add replaced permissions for user permissions

src/main/java/org/folio/roles/service/capability/CapabilityReplacementsService.java, src/test/java/org/folio/roles/it/PermissionReplacementIT.java, src/test/java/org/folio/roles/service/capability/CapabilityReplacementsServiceTest.java
https://folio-org.atlassian.net/browse/MODROLESKC-234
Ensure replaced capabilities/capability-sets get removed from the system - both user/role assignments are removed, and capabilities/capability-sets themselves are deleted. …
=> MODROLESKC-234: Remove replaced capabilities and capability sets

src/main/java/org/folio/roles/integration/kafka/CapabilityEventProcessor.java, src/test/java/org/folio/roles/integration/kafka/CapabilityEventProcessorTest.java, src/test/java/org/folio/roles/it/KafkaMessageListenerIT.java, src/test/java/org/folio/roles/it/PermissionReplacementIT.java, src/test/java/org/folio/roles/it/RoleCapabilitySetUpdateIT.java, src/test/java/org/folio/roles/it/UserCapabilitySetUpdateIT.java, src/test/resources/json/kafka-events/be-capability-event.json, src/test/resources/sql/kafka-message-listener-it/all-capabilities.sql
In order to support cases when PermissionSets defined in the back-end modules are used in the UI-modules, we need to changes the capability and capability set creation in mod-roles-keycloak
modify CapabilitySetDescriptor creation in `CapabilityEventProcessor`
=> SubPermissions processing

pom.xml
https://folio-org.atlassian.net/browse/MODROLESKC-248
Upgrade spring-kafka from 3.2.4 to 3.3.0 to fix security vulnerability in kafka-clients:
* https://www.cve.org/CVERecord?id=CVE-2024-31141 Files or Directories Accessible to External Parties
Upgrade folio-spring-support from 8.2.1 to 8.2.2 fixing security vulnerability in spring-security-crypto:
* https://www.cve.org/CVERecord?id=CVE-2024-38827 Authorization Bypass
Fix security vulnerabilities.
Bump the version of dependencies to a fixed version.
=> MODROLESKC-248: spring-kafka 3.3.0, folio-spring-support 8.2.2 fix vulns

src/main/java/org/folio/roles/service/capability/CapabilityEventHandler.java, src/main/java/org/folio/roles/service/capability/CapabilityReplacementsService.java, src/main/java/org/folio/roles/service/capability/CapabilitySetEventHandler.java, src/main/java/org/folio/roles/service/permission/FolioPermissionService.java, src/test/java/org/folio/roles/service/permission/FolioPermissionServiceTest.java
https://folio-org.atlassian.net/browse/MODROLESKC-257
Fix duplicate key error on updating permissions which prevents the service from properly handling permission update Kafka event.
Also added extra logging to deletion of deprecated capabilities and capability-sets.
Ideally, all the PRs involved in breaking changes would be merged on the …
=> MODROLESKC-257

src/main/java/org/folio/roles/service/capability/UserCapabilityService.java, src/test/java/org/folio/roles/service/capability/UserCapabilityServiceTest.java
Previously, permissions in Keycloak for an existing capability were not updated, even though the capability was being updated in the FOLIO system. With this update, the system will now attempt to create the permission, and if it already exists, we will get the warning  "Permission for the user already exists." but if not it would be create it 
Remove the logic that skips permission creation for existing endpoints based on capabilities. Instead, the system will attempt to create permissions for existing capabilities if an update is required.
If there are breaking changes, please **STOP** and consider …
=> MODROLESKC-233: Update User Capability logic to update permission for user in the Keycloak for existing capabilities

src/main/java/org/folio/roles/repository/CapabilityRepository.java, src/main/java/org/folio/roles/repository/LoadablePermissionRepository.java, src/main/java/org/folio/roles/service/capability/CapabilityReplacementsService.java, src/main/java/org/folio/roles/service/capability/CapabilityService.java, src/test/java/org/folio/roles/service/capability/CapabilityReplacementsServiceTest.java, src/test/java/org/folio/roles/support/LoadablePermissionUtils.java
https://folio-org.atlassian.net/browse/MODROLESKC-254
Fix issue where loadable role permissions in DB prevent capability replacement logic from deleting old replaced capabilities or capability sets.
environment. …
=> MODROLESKC-254: fix replacement of loadable permissions

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/roles/controller/RoleCapabilityController.java, src/main/java/org/folio/roles/controller/RoleCapabilitySetController.java, src/main/java/org/folio/roles/controller/UserCapabilityController.java, src/main/java/org/folio/roles/controller/UserRoleController.java, src/main/resources/swagger.api/mod-roles-keycloak.yaml, src/test/java/org/folio/roles/controller/RoleCapabilityControllerTest.java, src/test/java/org/folio/roles/controller/RoleCapabilitySetControllerTest.java, src/test/java/org/folio/roles/controller/UserCapabilityControllerTest.java, src/test/java/org/folio/roles/controller/UserCapabilitySetControllerTest.java, src/test/java/org/folio/roles/controller/UserRoleControllerTest.java, src/test/java/org/folio/roles/it/RoleCapabilityIT.java, src/test/java/org/folio/roles/it/RoleCapabilitySetIT.java, src/test/java/org/folio/roles/it/RoleKeycloakIT.java, src/test/java/org/folio/roles/it/UserCapabilityIT.java, src/test/java/org/folio/roles/it/UserCapabilitySetIT.java
https://folio-org.atlassian.net/browse/MODROLESKC-268
Fixed incorrectly named permissions in module descriptor, removed unnecessary endpoints that called for duplication of permissions, updated versions and tests accordingly. …
=> MODROLESKC-268: Fix module descriptor, remove unnecessary endpoints

src/main/resources/reference-data/roles/cataloger-linked-data-editor.json, src/test/java/org/folio/roles/it/ReferenceDataIT.java
To create an out-of-box role `Cataloger - Linked Data Editor`. 
Folio administrative staff should be able to assign this role to Linked Data catalogers.
Related links:
Linked data application descriptor: [app-linked-data](https://github.com/folio-org/app-linked-data)
Backend repo: [mod-linked-data/](https://github.com/folio-org/mod-linked-data/)
Frontend repo: [ui-ld-folio-wrapper](https://github.com/folio-org/ui-ld-folio-wrapper)
Add a new role definition file similar to other existing defintions
Please note that linked-data is not part of platform complete application. Do we need to do anything special in this case?
N/A
- Does this …
=> MODROLESKC-271: Add 'Cataloger - Linked Data Editor' role

descriptors/ModuleDescriptor-template.json, src/main/resources/permissions-view-edit-mapping/capabilities/capabilities-to-view-edit-capabilities.json, src/test/java/org/folio/roles/service/migration/ManagePermissionsResolverTest.java
Explain why these changes are needed and link the related issue (e.g., https://folio-org.atlassian.net/browse/PROJ-123).
[MODROLESKC-295](https://folio-org.atlassian.net/browse/MODROLESKC-295) - Inconsistent naming of permissions
Provide a brief technical summary of the changes.
---
=> MODROLESKC-295 -  Inconsistent naming of permissions

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/roles/controller/LoadableRoleController.java, src/main/java/org/folio/roles/domain/entity/LoadableRoleEntity.java, src/main/java/org/folio/roles/repository/LoadableRoleRepository.java, src/main/java/org/folio/roles/service/loadablerole/LoadableRoleService.java, src/main/java/org/folio/roles/service/migration/MigrationRoleCreator.java, src/main/java/org/folio/roles/service/role/RoleEntityService.java, src/main/java/org/folio/roles/service/role/RoleService.java, src/main/resources/changelog/changelog-master.xml, src/main/resources/changelog/changes/add-loaded-from-file-field-to-loadable-roles.xml, src/main/resources/swagger.api/mod-roles-keycloak.yaml, src/main/resources/swagger.api/schemas/role/roles.json, src/test/java/org/folio/roles/it/LoadableRoleProcessingIT.java, src/test/java/org/folio/roles/it/RoleKeycloakIT.java, src/test/java/org/folio/roles/service/loadablerole/LoadableRoleServiceTest.java, src/test/java/org/folio/roles/service/migration/MigrationRoleCreatorTest.java, src/test/java/org/folio/roles/service/role/RoleEntityServiceTest.java, src/test/java/org/folio/roles/service/role/RoleServiceTest.java, src/test/java/org/folio/roles/support/RoleUtils.java
https://folio-org.atlassian.net/browse/MODROLESKC-301
It was decided to re-use Loadable Role mechanism for system user’s roles, instead of implementing something similar to dummy capabilities.
- add PUT `/loadable-roles` to create or update loadable roles
- add tests
- restrict update|create|delete Default roles via roles rest API 
- increase interface version
---
=> MODROLESKC-301: add upsert rest API method to create default loadable roles

src/main/java/org/folio/roles/integration/keyclock/RealmConfigurationProvider.java, src/test/java/org/folio/roles/integration/keyclock/RealmConfigurationProviderTest.java
Update the code to reflect the changes done in application-poc-tools in this PR: https://github.com/folio-org/applications-poc-tools/pull/218
US: [FSSP-1](https://folio-org.atlassian.net/browse/FSSP-1)
* Replace `NotFoundException` with the more general `SecureStoreServiceException`, as it encompasses a broader range of scenarios— not just when a secret is missing, but also when there are issues communicating with the secure store.
=> FSSP-1 Adopt to changes in secure store

src/main/java/org/folio/roles/service/role/RoleService.java, src/test/java/org/folio/roles/it/RoleKeycloakIT.java, src/test/java/org/folio/roles/service/role/RoleServiceTest.java
Default roles can be deleted. We have to fix this.
https://folio-org.atlassian.net/browse/MODROLESKC-301
- change source to check role type before deletion (keycloak -> mod-roles-keycloak db)
- fix tests 
---
=> MODROLESKC-301: fix default roles deletion

NEWS.md, src/main/java/org/folio/roles/service/migration/RolePermissionAssignor.java, src/test/java/org/folio/roles/service/migration/RolePermissionAssignorTest.java
Fix for [MODROLESKC-323](https://folio-org.atlassian.net/browse/MODROLESKC-323)
- Do not filter out technical capabilities during the migration
---
=> MODROLESKC-323: BE permission is not properly converted to capabilities after migration to Eureka

NEWS.md, src/main/java/org/folio/roles/integration/kafka/CapabilitySetDescriptorService.java, src/main/java/org/folio/roles/mapper/entity/CapabilityEntityMapper.java, src/main/java/org/folio/roles/service/capability/CapabilityEventHandler.java, src/main/java/org/folio/roles/service/capability/CapabilityResolver.java, src/test/java/org/folio/roles/integration/kafka/CapabilitySetDescriptorServiceTest.java, src/test/java/org/folio/roles/it/CapabilityReplacesIntegrityIT.java, src/test/java/org/folio/roles/it/KafkaCapabilityEventUpsertIT.java, src/test/java/org/folio/roles/service/capability/CapabilityEventHandlerTest.java, src/test/java/org/folio/roles/service/capability/CapabilityResolverTest.java, src/test/resources/json/kafka-events/corrupted-capabilities/correct-capability-event-create.json, src/test/resources/json/kafka-events/corrupted-capabilities/correct-capability-event-update.json, src/test/resources/json/kafka-events/corrupted-capabilities/replacement-event-create.json, src/test/resources/json/kafka-events/corrupted-capabilities/replacement-event-update.json, src/test/resources/json/keycloak/role-loadable-processing-realm.json, src/test/resources/sql/corrupted-capabilities/populate-corrupted-capabilities-and-sets.sql, src/test/resources/sql/corrupted-capabilities/populate-data-replacement.sql
For existing systems, the database likely contains corrupted data from the old logic. We need to analyze this and create a strategy to fix the old dummy capabilities that have the wrong folio_permission.
https://folio-org.atlassian.net/browse/MODROLESKC-316
- update corrupted capabilities
- add tests that cover updating corrupted records
- skip deletion of corrupted capabilities 
---
=> MODROLESKC-316: add idempotency for Capability event processing
