pom.xml

Upgrade Keycloak to v23.0.3 for integration tests and `keycloak-admin-client` to v23.0.3
- Upgrade Keycloak to v23.0.3 for integration tests
- Upgrade `keycloak-admin-client` to v23.0.3
environment. Communication is …

MODROLESKC-15 Upgrade Keycloak client to v23.0.3

---

pom.xml
src/main/java/org/folio/roles/domain/entity/BasePolicyEntity.java
src/main/java/org/folio/roles/domain/entity/CapabilityEntity.java
src/main/java/org/folio/roles/domain/entity/CapabilitySetEntity.java
src/main/java/org/folio/roles/domain/entity/EmbeddableEndpoint.java
src/main/java/org/folio/roles/domain/entity/type/EntityCapabilityAction.java
src/main/java/org/folio/roles/domain/entity/type/EntityCapabilityType.java
src/main/java/org/folio/roles/integration/kafka/configuration/KafkaConfiguration.java
src/main/java/org/folio/roles/repository/CapabilityRepository.java
src/main/java/org/folio/roles/repository/generators/FolioUuidGeneratorImpl.java
src/main/java/org/folio/roles/service/capability/CapabilityService.java
src/main/resources/changelog/changelog-master.xml
src/main/resources/changelog/changes/update_timestamp_fields_to_timestamp_with_zone.xml
src/test/java/org/folio/roles/repository/generators/FolioUuidGeneratorImplTest.java
src/test/java/org/folio/roles/service/capability/CapabilityServiceTest.java
src/test/java/org/folio/roles/support/CapabilitySetUtils.java
src/test/java/org/folio/roles/support/CapabilityUtils.java

https://issues.folio.org/browse/MODROLESKC-22
- upgrade Spring Boot parent
- upgrade Folio support and app-poc-tools libs
- migrate timestamp to timestamp with timezone
- pass String instead of array into native query to solve binding problem
- create Entity* enums to use Uppercase values 
Ideally, all the PRs involved in breaking changes …

MODROLESKC-22 upgrade Spring Boot 3.2.1

---

src/main/resources/swagger.api/examples/requests/capabilitiesUserRequest.json
src/main/resources/swagger.api/examples/requests/rolesUserRequest.json
src/main/resources/swagger.api/examples/responses/rolesUser.json
src/main/resources/swagger.api/schemas/capability/user/userCapabilitiesRequest.json

Inaccurate examples have been found and need to be corrected.
- fix some examples for schema

FIX: update examples for API docs

---

src/main/java/org/folio/roles/service/permission/RolePermissionService.java
src/main/java/org/folio/roles/service/permission/UserPermissionService.java
src/main/java/org/folio/roles/service/policy/PolicyService.java
src/test/java/org/folio/roles/it/RoleCapabilityIT.java
src/test/java/org/folio/roles/it/RoleCapabilitySetIT.java
src/test/java/org/folio/roles/it/UserCapabilityIT.java
src/test/java/org/folio/roles/it/UserCapabilitySetIT.java
src/test/java/org/folio/roles/service/permission/RolePermissionServiceTest.java
src/test/java/org/folio/roles/service/permission/UserPermissionServiceTest.java
src/test/java/org/folio/roles/service/policy/PolicyServiceTest.java
src/test/resources/json/keycloak/role-capability-realm.json
src/test/resources/json/keycloak/user-capability-realm.json
src/test/resources/sql/populate-role-policy.sql
src/test/resources/sql/populate-user-policy.sql

Fixes capability assignment after role renaming.
- Use for user/role policy and permissions actual identifier instead of username/role name.
- Fix integration and unit tests
- Add a new integration test to preserve implementation …

MODROLESKC-131 Fix capability assigment after role rename

---

src/main/java/org/folio/roles/service/permission/FolioPermissionService.java
src/main/java/org/folio/roles/service/permission/PermissionMigrationService.java
src/test/java/org/folio/roles/service/permission/FolioPermissionServiceTest.java

folio_permissions attribute can have multiple values
JIRA: https://issues.folio.org/browse/MGRENTITLE-26
- Refactoring resource attributes processing to support multi-value folio_permissions
- Add missing ui permission prefix - settings
- Update tests
Ideally, all the PRs involved in breaking changes would be merged on the same day to avoid …

[MGRENTITLE-26] Refactoring folio_permissions attribute processing

---

pom.xml

Raises folio-backend-testing to v1.3.0-SNAPSHOT
- Raise `folio-backend-testing` to v1.3.0-SNAPSHOT
inter-team …

KEYCLOAK-6 Raise folio-backend-testing to v1.3.0-SNAPSHOT

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
.github/workflows/api-schema-lint.yml
src/main/resources/swagger.api/mod-roles-keycloak.yaml

[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)

FOLIO-3678 MODROLESKC-1 Use GitHub Workflows api-lint and api-schema-lint and api-doc

---

src/main/resources/changelog/changelog-master.xml
src/main/resources/changelog/changes/update-role-deletion-constraints.xml
src/test/java/org/folio/roles/it/PolicyIT.java
src/test/java/org/folio/roles/it/RoleKeycloakIT.java
src/test/resources/sql/populate-role-capability-for-deletion.sql
src/test/resources/sql/populate-roles-for-policies-batch.sql
src/test/resources/sql/populate-user-role-for-deletion.sql

Delete role with its child associations
Add onDelete cascade constraints to role_capability, user_roles, policy_roles associations
environment. Communication is paramount if that is to be achieved, especially as the number …

[MODROLESKC-157]: fix role deletion 

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODROLESKC-162
- update NEWS.md
While …

MODROLESKC-162: release 1.1.0

---

src/main/java/org/folio/roles/integration/kafka/CapabilitySetDescriptorService.java
src/main/java/org/folio/roles/repository/CapabilitySetRepository.java
src/main/java/org/folio/roles/service/capability/CapabilityService.java
src/main/java/org/folio/roles/service/capability/CapabilitySetService.java
src/test/java/org/folio/roles/integration/kafka/CapabilitySetDescriptorServiceTest.java
src/test/java/org/folio/roles/it/CapabilitySetIT.java
src/test/java/org/folio/roles/it/KafkaMessageListenerIT.java
src/test/java/org/folio/roles/service/capability/CapabilityServiceTest.java
src/test/java/org/folio/roles/service/capability/CapabilitySetServiceTest.java
src/test/resources/json/kafka-events/be-capability-event-v2.json
src/test/resources/sql/kafka-message-listener-it/all-permissions.sql
src/test/resources/sql/truncate-permission-table.sql

Updates capability or capability set if a duplicate is found by name.
- Update capability / capability set if a duplicate is found by name
- Update unit and integration tests
environment. Communication is paramount if that …

MODROLESKC-171 Update capabilities instead of skipping

---

src/main/java/org/folio/roles/integration/kafka/CapabilityEventProcessor.java

Added Java doc to the CapabilityEventProcessor method

Tech Capabilities JavaDoc Added

---

NEWS.md
src/main/java/org/folio/roles/controller/PermissionsUsersController.java
src/main/java/org/folio/roles/repository/CapabilityRepository.java
src/main/java/org/folio/roles/service/capability/CapabilityService.java
src/main/resources/application.yml
src/main/resources/swagger.api/mod-roles-keycloak.yaml
src/test/java/org/folio/roles/controller/PermissionsUsersControllerTest.java
src/test/java/org/folio/roles/it/PermissionsUserIT.java
src/test/java/org/folio/roles/service/capability/CapabilityServiceTest.java

https://folio-org.atlassian.net/browse/MODUSERSKC-29
The user-permissions endpoint should be adjusted in the scope of the task.
- add the parameter to filter permissions by
- adjust tests

MODUSERSKC-29: adjust permissions user

---

src/main/resources/changelog/changelog-master.xml
src/main/resources/changelog/changes/update-role-capability-role-constraint.xml
src/test/java/org/folio/roles/it/RoleKeycloakIT.java
src/test/resources/sql/populate-role-capability-and-capability-set-for-deletion.sql

Fix role deletion
Add On Delete Cascade constraint to `role_capability_set` with `role` association.
inter-team …

MODROLESKC-157: fix role deletion

---

src/main/resources/folio-permissions/mappings-overrides.json

There are a handful of places where we need to add capability mapping overrides due to wrong permission namings
[MODROLESKC-186](https://folio-org.atlassian.net/browse/MODROLESKC-186)
Add missing capabilities to the mapping-overrides file …

MODROLESKC-186: Capability mapping overrides

---

NEWS.md
pom.xml

- Release 1.3.1
- Prepare for the next iteration

Release 1.3.1

---

Jenkinsfile

Related Jira Ticket:
[RANCHER-1515: prepare & merge PRs for RANCHER-1502 part1](https://folio-org.atlassian.net/browse/RANCHER-1515)

RANCHER-1515: pack application to Docker Image and upload it to ECR

---

src/main/resources/folio-permissions/mappings-overrides.json

https://folio-org.atlassian.net/browse/EUREKA-96
There is missing permission for the desired action.
- add mapping for invoice.item.cancel
environment. Communication is paramount if that is to be achieved, especially as the …

EUREKA-96: add mapping for invoice.item.cancel

---

src/main/resources/folio-permissions/mappings-overrides.json

Add mapping for `lists.item.export.post`
While it's helpful for reviewers to …

EUREKA-143: add mapping for lists.item.export.post

---

src/main/resources/folio-permissions/mappings-overrides.json

Fix 403 when call `GET licenses/files/{id}/raw`
Add mapping for `licenses.files.item.download`
inter-team …

EUREKA-177: Add mapping for licenses.files.item.download

---

src/main/resources/folio-permissions/mappings-overrides.json

Add mapping for `lists.item.refresh.cancel`
While it's helpful for reviewers …

EUREKA-155: add mapping for lists.item.refresh.cancel

---

src/main/resources/folio-permissions/mappings-overrides.json

Add mapping for `lists.item.export.cancel`
While it's helpful for reviewers to …

EUREKA-143: add mapping for lists.item.export.cancel

---

pom.xml

Upgrade keycloak client to `v25.0.1`
- Use `applicaiton-poc-tools` `v1.5.3-SNAPSHOT` with latest keycloak client …

KEYCLOAK-11 Upgrade keycloak client to v25.0.1

---

src/main/java/org/folio/roles/integration/keyclock/KeycloakRoleService.java
src/main/java/org/folio/roles/service/loadablerole/LoadableRoleCapabilityAssignmentHelper.java
src/main/java/org/folio/roles/service/loadablerole/LoadableRoleCapabilityAssignmentProcessor.java
src/main/java/org/folio/roles/service/loadablerole/LoadableRoleService.java
src/main/java/org/folio/roles/utils/CapabilityUtils.java

Follow-up changes to fix small issues for [MODROLESKC-168](https://folio-org.atlassian.net/browse/MODROLESKC-168)
* ignore technical capabilities
* safely delete roles
* always check for updated permissions
environment. …

MODROLESKC-168 follow-up changes to main implementation: ignore technical capabilities, safely delete roles

---

NEWS.md
pom.xml

Fix liquibase error for creating new source type

Release v1.4.4 with Liquibase fix

---

src/main/resources/folio-permissions/mappings-overrides.json

Add missing mappings
Add mappings for permissions:
- ui-consortia-settings.consortium-manager.share
- ui-consortia-settings.settings.networkOrdering.view
- ui-data-export.edit
- ui-data-export.view
- ui-data-export.settings.view
- ui-data-export.settings.edit
Tested on **evrk2:**
Ideally, all the PRs involved in breaking changes would be …

EUREKA-219: add missing mappings

---

pom.xml
src/main/java/org/folio/roles/integration/keyclock/configuration/KeycloakConfiguration.java
src/test/java/org/folio/roles/it/DisableHostnameVerificationConfig.java

Bump up applications-poc-tools dependencies to 1.5.6 to support Hostname Verification for TLS connections

Bump up applications-poc-tools dependencies to 1.5.6

---

README.md
src/main/resources/folio-permissions/mappings-overrides.json

Added permission to Capability mappings for non-standard mod-agreements permissions. Added ReadMe section describing permission mapping functionality.
This is needed to fix the issue of multiple mod-agreements permissions resulting being mapped to capabilities with overlapping names.
Custom permission mappings were added. Also permission mapping mechanism itself was documented in ReadMe.
- Are the Rally stories under …

EUREKA-287: Fix overlapping capabilities for mod-agreement

---

NEWS.md
pom.xml

https://folio-org.atlassian.net/browse/MODROLESKC-220

Release 1.4.6

---

pom.xml
src/test/java/org/folio/roles/integration/kafka/CapabilityKafkaEventHandlerTest.java

Increases keycloak-admin-client to v25.0.6
- Increases keycloak-admin-client to v25.0.6
- Use the latest snapshot versions of `applications-poc-tools` library components
environment. Communication is paramount if that is to …

KEYCLOAK-24 Increase keycloak-admin-client to v25.0.6

---

src/main/java/org/folio/roles/integration/kafka/CapabilityKafkaEventHandler.java
src/main/java/org/folio/roles/integration/kafka/CapabilitySetDescriptorService.java
src/main/java/org/folio/roles/repository/CapabilityRepository.java
src/main/java/org/folio/roles/repository/CapabilitySetRepository.java
src/main/java/org/folio/roles/service/capability/CapabilityService.java
src/main/java/org/folio/roles/service/capability/CapabilitySetService.java
src/main/java/org/folio/roles/utils/CapabilityUtils.java
src/test/java/org/folio/roles/integration/kafka/CapabilityKafkaEventHandlerTest.java
src/test/java/org/folio/roles/it/KafkaMessageListenerIT.java

https://folio-org.atlassian.net/browse/MODROLESKC-236
For cases when upgrade of an application is done via un-install with "purge=false" and re-install of a newer version of app - we need to update app and module versions for capabilities that remained in DB to match new versions.
Ideally, all the PRs involved in breaking changes would be …

MODROLESKC-236: Update app+module versions for capabilities on re-entitling application

---

src/main/java/org/folio/roles/service/capability/CapabilityService.java
src/main/java/org/folio/roles/service/permission/UserPermissionService.java
src/test/java/org/folio/roles/service/permission/UserPermissionServiceTest.java

While it's helpful for reviewers to help identify potential problems, ensuring …

MODROLESKC-233: Revert the changes that were previously made.

---

src/main/java/org/folio/roles/integration/keyclock/KeycloakAuthorizationService.java
src/test/java/org/folio/roles/integration/keyclock/KeycloakAuthorizationServiceTest.java
src/test/java/org/folio/roles/it/RoleCapabilityIT.java
src/test/resources/json/keycloak/role-capability-realm-scope-not-found-for-resource.json

https://folio-org.atlassian.net/browse/MODROLESKC-243
Ensure that capabilities continue to be assigned to users even if the target resource scope not found. During the batch assignment process, if an error occurs with one capability, the assignment of the remaining capabilities should proceed without interruption.
- remove error if scope not found
- add warn log if scope not found
- add tests
- Are the Rally stories under …

MODROLESKC-243: handle scope not found error

---

src/main/java/org/folio/roles/service/capability/CapabilityReplacementsService.java
src/test/java/org/folio/roles/service/capability/CapabilityReplacementsServiceTest.java

https://folio-org.atlassian.net/browse/EUREKA-604
Properly handle capability replacements in case there exists a permission mapping override for given capability.
environment. Communication is paramount if that is to be …

EUREKA-604: Properly handle capability replacements

---

src/main/java/org/folio/roles/service/capability/CapabilityReplacementsService.java
src/test/java/org/folio/roles/base/BaseIntegrationTest.java
src/test/java/org/folio/roles/it/KafkaMessageListenerIT.java
src/test/resources/application-it.yml
src/test/resources/folio-permissions/mappings-overrides.json
src/test/resources/json/kafka-events/be-capability-event-replaced-perm-is-override.json

https://folio-org.atlassian.net/browse/MODROLESKC-262
- filter replacing override permissions
- add test

MODROLESKC-262: filter replacing override permissions

---

src/test/java/org/folio/roles/it/KafkaMessageListenerIT.java

https://folio-org.atlassian.net/browse/MODROLESKC-264
Not required changes should be reverted. 
- revert not required changes

MODROLESKC-262: revert not required changes

---

pom.xml
src/test/resources/application-it.yml

Increases version of `keycloak-admin-client` to `v26.0.4`, also implement a new version of keycloak in integration tests - `v26.1.0`
- Increases version of `keycloak-admin-client` to `v26.0.4`
- Increases version of `applications-poc-tools` to `v2.3.0-SNAPSHOT`
Ideally, all the PRs involved in breaking changes would be merged on the same …

KEYCLOAK-25 Raise keycloak-admin-client to v26.0.4

---

descriptors/ModuleDescriptor-template.json
src/main/java/org/folio/roles/controller/RoleCapabilityController.java
src/main/java/org/folio/roles/controller/RoleCapabilitySetController.java
src/main/java/org/folio/roles/controller/UserCapabilityController.java
src/main/java/org/folio/roles/controller/UserRoleController.java
src/main/resources/swagger.api/mod-roles-keycloak.yaml
src/test/java/org/folio/roles/controller/RoleCapabilityControllerTest.java
src/test/java/org/folio/roles/controller/RoleCapabilitySetControllerTest.java
src/test/java/org/folio/roles/controller/UserCapabilityControllerTest.java
src/test/java/org/folio/roles/controller/UserCapabilitySetControllerTest.java
src/test/java/org/folio/roles/controller/UserRoleControllerTest.java
src/test/java/org/folio/roles/it/RoleCapabilityIT.java
src/test/java/org/folio/roles/it/RoleCapabilitySetIT.java
src/test/java/org/folio/roles/it/RoleKeycloakIT.java
src/test/java/org/folio/roles/it/UserCapabilityIT.java
src/test/java/org/folio/roles/it/UserCapabilitySetIT.java

https://folio-org.atlassian.net/browse/EUREKASUP-44
Put back the endpoints that were deemed not used and were thus deleted - but were actually used by deployment automation.
This reverts commit 3ff3a4c083b46aadf0fb4c8d693ae923c4fea3b0. …

EUREKASUP-44 - Revert deletion of endpoints done in scope of MODROLESKC-268

---

pom.xml
src/main/java/org/folio/roles/domain/model/CapabilityReplacements.java
src/main/java/org/folio/roles/repository/CapabilityRepository.java
src/main/java/org/folio/roles/repository/CapabilitySetRepository.java
src/main/java/org/folio/roles/service/capability/CapabilityReplacementsService.java
src/main/java/org/folio/roles/service/capability/CapabilityService.java
src/main/java/org/folio/roles/service/capability/CapabilitySetService.java
src/main/java/org/folio/roles/service/loadablerole/LoadableRoleCapabilityAssignmentHelper.java
src/main/java/org/folio/roles/service/migration/RolePermissionAssignor.java
src/test/java/org/folio/roles/it/KafkaMessageListenerIT.java
src/test/java/org/folio/roles/service/capability/CapabilityReplacementsServiceTest.java
src/test/java/org/folio/roles/service/capability/CapabilityServiceTest.java
src/test/java/org/folio/roles/service/capability/CapabilitySetServiceTest.java
src/test/java/org/folio/roles/service/loadablerole/LoadableRoleCapabilityAssignmentHelperTest.java
src/test/java/org/folio/roles/service/migration/RolePermissionAssignorTest.java
src/test/java/org/folio/roles/support/CapabilityUtils.java
src/test/resources/json/kafka-events/be-capability-event-replaces-contains-same-capability-by-permission.json

https://folio-org.atlassian.net/browse/MODROLESKC-273
The same capability can be created from different permissions, which leads to collisions and logical issues
- move permission replacement logic from `capability.name` to `capability.permissionName`
- add tests
- fix tests
Ideally, all the PRs involved in breaking changes would be merged …

MODROLESKC-273: fix capability loss due to permissions overlap

---

Dockerfile
Jenkinsfile
pom.xml

Upgrade Java to version 21
While it's helpful for reviewers to help identify …

MODROLESKC-277: Upgrade Java to version 21.

---

src/main/java/org/folio/roles/service/capability/CapabilityReplacementsService.java

Bugfixing for [MODROLESKC-293](https://folio-org.atlassian.net/browse/MODROLESKC-293)
- avoid duplication exception by merging sets
---

MODROLESKC-293: ui-invoice uses backend permission to show/hide action - approve & pay not visible in action menu

---

src/main/java/org/folio/roles/service/capability/RoleCapabilityServiceImpl.java
src/main/java/org/folio/roles/service/capability/RoleCapabilitySetServiceImpl.java
src/test/java/org/folio/roles/service/capability/RoleCapabilityServiceImplTest.java
src/test/java/org/folio/roles/service/capability/RoleCapabilitySetServiceImplTest.java

https://folio-org.atlassian.net/browse/MODROLESKC-297
For sharing feature we are expecting capability/set assigned to role if there are at least one valid capability/set exists instead of stopping action. 
- throw error only all capabilities are not found, otherwise continue with found ones
---

[MODROLESKC-297] - Skip attaching capabilities to the shared role if they do not exist in the tenant.

---

src/main/java/org/folio/roles/domain/entity/CapabilityEntity.java
src/main/java/org/folio/roles/domain/entity/CapabilitySetEntity.java
src/main/java/org/folio/roles/integration/kafka/CapabilityEventProcessor.java
src/main/java/org/folio/roles/integration/kafka/CapabilitySetDescriptorService.java
src/main/java/org/folio/roles/integration/kafka/model/CapabilitySetDescriptor.java
src/main/resources/changelog/changelog-master.xml
src/main/resources/changelog/changes/add-visible-field-to-capabilities-and-capsets.xml
src/main/resources/changelog/changes/populate-visible-field-in-capabilities-and-capsets.xml
src/main/resources/swagger.api/schemas/capability/capability.json
src/main/resources/swagger.api/schemas/capability/capabilitySet.json
src/test/java/org/folio/roles/it/KafkaMessageListenerIT.java
src/test/resources/json/kafka-events/be-capability-event.json
src/test/resources/sql/capabilities/populate-capabilities.sql
src/test/resources/sql/capability-sets/populate-capability-sets.sql
src/test/resources/sql/kafka-message-listener-it/all-capabilities.sql
src/test/resources/sql/kafka-message-listener-it/partial-capabilities.sql

https://folio-org.atlassian.net/browse/MODROLESKC-291
Have a "visible" field in capabilties/capabilitysets, and properly pass permission visibility to corresponding capabilities/sets.
Take visibility from Kafka event payload with permissions and pass it along to corresponding capabilities/capabilitysets.
For already created capabilities+capabilitysets - take visibility from visible field of corresponding permissions in DB.
---

Modroleskc 291

---

NEWS.md
src/main/java/org/folio/roles/integration/kafka/CapabilityEventProcessor.java
src/main/java/org/folio/roles/integration/kafka/CapabilityKafkaEventHandler.java
src/main/java/org/folio/roles/integration/kafka/CapabilitySetDescriptorService.java
src/main/java/org/folio/roles/integration/kafka/mapper/CapabilitySetMapper.java
src/main/java/org/folio/roles/integration/kafka/model/CapabilitySetDescriptor.java
src/main/java/org/folio/roles/mapper/entity/CapabilitySetEntityMapper.java
src/main/java/org/folio/roles/repository/PermissionRepository.java
src/main/java/org/folio/roles/service/capability/CapabilitySetService.java
src/main/java/org/folio/roles/service/capability/RoleCapabilitySetServiceImpl.java
src/main/java/org/folio/roles/service/loadablerole/LoadableRoleCapabilityAssignmentProcessor.java
src/main/java/org/folio/roles/service/permission/PermissionOverrider.java
src/test/java/org/folio/roles/integration/kafka/CapabilityEventProcessorTest.java
src/test/java/org/folio/roles/integration/kafka/CapabilitySetDescriptorServiceTest.java
src/test/java/org/folio/roles/it/DummyCapabilityIT.java
src/test/java/org/folio/roles/it/LoadableRolesWithDummyCapabilitiesIT.java
src/test/java/org/folio/roles/it/NestedCapabilitySetIT.java
src/test/java/org/folio/roles/support/CapabilityUtils.java
src/test/resources/json/kafka-events/be-capability-event.json
src/test/resources/json/kafka-events/dummy-capability-replaced-real-capability-event.json
src/test/resources/json/kafka-events/dummy-capability-set-event.json
src/test/resources/json/kafka-events/loadable-role-nested-dummy-set-event.json
src/test/resources/json/kafka-events/loadable-role-real-nested-set-event.json
src/test/resources/json/kafka-events/nested-capability-set-cyclic-event.json
src/test/resources/json/kafka-events/nested-capability-set-deeper-event.json
src/test/resources/json/kafka-events/nested-capability-set-event.json
src/test/resources/json/keycloak/role-loadable-processing-realm.json

https://folio-org.atlassian.net/browse/MODROLESKC-313
- refactoring for dummy capability creation
- fix several data inconsistencies bugs
- add IT test for dummy capabilities
- update tests
---

MODROLESKC-313: fix missing capabilities in capability sets

---

NEWS.md
pom.xml
src/test/java/org/folio/roles/it/DummyCapabilityReplacementCollapseIT.java
src/test/java/org/folio/roles/it/NestedCapabilitySetIT.java
src/test/resources/json/kafka-events/mod-items-1.0.0-create-event.json
src/test/resources/json/kafka-events/mod-items-2.0.0-update-event.json
src/test/resources/json/kafka-events/ui-app-create-event.json

https://folio-org.atlassian.net/browse/MODROLESKC-305
Two test cases were covered by the integration test. There were no code changes. The issue described in the task was cross-fixed in previous PRs.
- add 2 integration testes
---

MODROLESKC-305: cross module dummy capability replacement

---

src/main/resources/application.yml

[MODROLESKC-326](https://folio-org.atlassian.net/browse/MODROLESKC-326) - Use SECURE_STORE_ENV, not ENV, for secure store key
Provide a brief technical summary of the changes.
---

MODROLESKC-326 - set SECURE_STORE_ENV with ENV value
